name: ChatControl
main: kangarko.chatcontrol.ChatControl
version: 5.4.1
author: kangarko
soft-depend: [AuthMe, Essentials, Multiverse-Core, ProtocolLib, SimpleClans, Towny, Vault]
commands: 
  chatcontrol:
    aliases: [chatc, chc]
    description: Main ChatControl command. Type /chatcontrol list for commands.
permissions:
    chatcontrol.notify.overrideranged:
        default: false
    chatcontrol.notify.whenmentioned:
        default: true
        description: Play a sound when the player is notified and the function is enabled.
    chatcontrol.broadcaster.view:
        default: true
        description: View timed messages from auto broadcaster.